triggerFile: config/Run3_2024/triggers.yaml
corrections:
  lumi: { stage: AnaTuple }
  xs: { stage: AnaTuple }
  gen: { stage: AnaTuple }
  pu:
    stages: [ AnaTuple, AnaTupleMerge ]
    enabled:
      AnaTuple: true
      AnaTupleMerge: false
  base: { stage: AnaTupleMerge }
  tauID: { stage: HistTuple }
  tauES: { stage: AnaTuple }
  mu:
    stage: HistTuple
    columns:
      pfRelIso04_all: Muon_pfRelIso04_all
      tightId: Muon_tightId
      tkRelIso: Muon_tkRelIso
      highPtId: Muon_highPtId
      mediumId: Muon_mediumId
      looseId: Muon_looseId
  trigger:
    stage: HistTuple
    mode: efficiency
  ele: { stage: HistTuple }
  muScaRe: { stage: AnaTuple, mu_pt_for_ScaReApplication: "nano" }
  eleES: { stage: AnaTuple }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true
  btag:
    stages: [ AnaTuple ]
    modes:
      AnaTuple: none
    tagger: UParTAK4
    jetCollection: centralJet
  dy_hhbbtautau:
    stages: [ HistTuple ]
    processes: [ DY_M_10to50, DYto2E_M_50, DYto2Mu_M_50, DYto2Tau_M_50 ]
  bosonicRecoil:
    stage: HistTuple
    method: QuantileMapHist
    apply_systematics: true
