anaTupleDef: AnaProd/anaTupleDef.py
histTupleDef: Analysis/histTupleDef.py
analysis_import: Analysis.hh_bbtautau
phys_model: BaseModel
use_cmssw_env_AnaTupleProduction: true

bundles:
  core:
    period_specific: false
    patterns:
      - FLAF
      - AnaProd
      - Analysis
      - config
      - env.sh
      - soft/flaf_env
      - HHbtag
      - Corrections
      - ClassicSVfit
      - SVfitTF
      - HHKinFit2
      - include
  cmssw:
    period_specific: false
    patterns:
      - soft/CMSSW_16_0_6
  inputFileList:
    period_specific: true
    patterns:
      - data/{version}/InputFileTask/{period}
    task_requires:
      module: FLAF.AnaProd.tasks
      class: InputFileTask
  AnaTupleFileList:
    period_specific: true
    patterns:
      - data/{version}/AnaTupleFileListBuilderTask/{period}
      - data/{version}/AnaTupleFileListTask/{period}
    task_requires:
      module: FLAF.AnaProd.tasks
      class: AnaTupleFileListBuilderTask
  inference:
    period_specific: false
    patterns:
      - inference
      - StatInference

WLCGFileSystem:
  remotePathCacheHost: cms-flaf.cern.ch
  remotePathCachePort: 5000
  localPathCacheValidity: 600
  verbose: 0

runTokenServer:
  host: cms-flaf.cern.ch
  port: 5007

nEventsPerFile:
  data: 1000000
  signals: 100000
  backgrounds: 100000

signal_types:
  - HHnonRes
  # - GluGluToRadion
  # - GluGluToBulkGraviton
  # - VBFToRadion
  # - VBFToBulkGraviton
genuineTau_SFtype:
  eTau: dm
  muTau: dm
  tauTau: dm
deepTauWPs:
  eTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium
  muTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium
  tauTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium

corrections:
  lumi: { stage: AnaTuple }
  xs: { stage: AnaTuple }
  gen: { stage: AnaTuple }
  pu:
    stages: [ AnaTuple, AnaTupleMerge ]
    enabled:
      AnaTuple: true
      AnaTupleMerge: false
  base: { stage: AnaTupleMerge }
  tauID: { stage: HistTuple }
  tauES: { stage: AnaTuple }
  mu:
    stage: HistTuple
    columns:
      pfRelIso04_all: Muon_pfRelIso04_all
      tightId: Muon_tightId
      tkRelIso: Muon_tkRelIso
      highPtId: Muon_highPtId
      mediumId: Muon_mediumId
      looseId: Muon_looseId
  trigger:
    stage: HistTuple
    mode: efficiency
  ele: { stage: HistTuple }
  muScaRe: { stage: AnaTuple, mu_pt_for_ScaReApplication: "nano" }
  eleES: { stage: AnaTuple }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true
  btag:
    stages: [ AnaTuple ]
    modes:
      AnaTuple: shape
    tagger: particleNet
    jetCollection: centralJet
  dy_hhbbtautau:
    stages: [ HistTuple ]
    processes: [ DY_M_10to50, DYto2E_M_50, DYto2Mu_M_50, DYto2Tau_M_50 ]
    njets_branch: nBJets
  bosonicRecoil:
    stage: HistTuple
    method: QuantileMapHist # Rescaling
    apply_systematics: true

extraFormat_for_triggerMatchingAndSF:
  pt: "nano"
muon_pt_for_presel: "nano"
mu_pt_for_triggerMatchingAndSF: "nano"
mu_pt_for_selection: "pt"
mu_pt_for_definitions: "ScaRe" # here options are different: corr, nano, bsConstrainedPt, roccor
muonID_WP_for_triggerSF: "Tight" # only medium or tight for trigger SF, both iso and ID
muIDWP: "Tight"
muIsoWP: "Tight"

histTuple_flavor: default
histTuple_flavors:
  default:
    fullResolution_variables: [ ]
    variables:
      - tau1_pt
      - tau1_eta
      - tau2_pt
      - tau2_eta
      - b1_pt
      - b1_eta
      - b2_pt
      - b2_eta
      - tautau_m_vis
      - bb_m_vis
      - met_pt
      - nBJets
      - nJet
  CI:
    fullResolution_variables: [ ]
    variables:
      - tau1_pt
      - ggF_DNN_HH

treeName: "Events"

region: SR
region_default: SR
custom_regions: QCDRegions
custom_categories: ""
custom_subcategories: [ ]

plot_wantQCD: true

channelSelection:
  - eTau
  - muTau
  - tauTau
  - eE
  - eMu
  - muMu

met_type: "PuppiMET"
deepTauVersion: 2p5
channels: ""
QCDRegions:
  - OS_Iso
  - SS_Iso
  - OS_AntiIso
  - SS_AntiIso
boosted_categories: [ ]
categories:
  - inclusive
  - baseline
  - boosted
  - res2b
  - res1b

requireHbbJets: False
storeExtraJets: False
storeVBFJets: True
storeExtraTaus: True
deepTauYears:
  v2p1: 2017
  v2p5: 2018

all_channels:
  - eTau
  - muTau
  - muMu
  - tauTau
  - eE
  - eMu

gen_channels:
  eTau:
    - 3
    - 5
  muTau:
    - 4
    - 5
  tauTau:
    - 5
    - 5

channelDefinition:
  eTau: 13
  muTau: 23
  tauTau: 33
  eE: 11
  eMu: 12
  muMu: 22

triggers:
  eTau: [ singleEle, etau ]
  muTau: [ singleMu, mutau ]
  tauTau: [ ditau, ditaujet ]
  eE: [ singleEle ]
  eMu: [ singleMu ]
  muMu: [ singleMu ]

hist_triggers:
  eTau:
    default: ( HLT_singleEle && Legacy_region )  # ( ( (HLT_singleEle || HLT_etau ) && Legacy_region ) || (HLT_singleTau && SingleTau_region && !Legacy_region) || (HLT_MET && (!(Legacy_region) && !(SingleTau_region)) ))
  muTau:
    default: (HLT_singleMu && Legacy_region)  # (( (HLT_singleMu || HLT_mutau ) && Legacy_region ) || (HLT_singleTau && SingleTau_region && !Legacy_region) || (HLT_MET && (!(Legacy_region) && !(SingleTau_region)) ))
  tauTau:
    # default: ( ( (HLT_ditau || HLT_ditaujet) && Legacy_Region ) ) # || (HLT_MET && !(Legacy_Region) ) )
    default: (HLT_ditau && Legacy_region)  # ((HLT_ditau && Legacy_region) || (HLT_singleTau && SingleTau_region && !Legacy_region) || (HLT_MET && (!(Legacy_region) && !(SingleTau_region)) ) )
  eE:
    default: (HLT_singleEle && SingleEle_region)
  eMu:
    default: (HLT_singleMu && SingleMu_region)  # ((HLT_singleEle && SingleEle_region) || (HLT_singleMu && SingleMu_region))
  muMu:
    default: (HLT_singleMu && SingleMu_region)

# https://github.com/LLRCMS/KLUBAnalysis/blob/10821fdc58f6bdb68b0142740f05b8c9f6e23bf9/config/selectionCfg_MuTau_UL18.cfg
# https://github.com/LLRCMS/KLUBAnalysis/blob/10821fdc58f6bdb68b0142740f05b8c9f6e23bf9/config/selectionCfg_TauTau_UL18.cfg
# https://github.com/LLRCMS/KLUBAnalysis/blob/10821fdc58f6bdb68b0142740f05b8c9f6e23bf9/test/skimNtuple_HHbtag.cpp#L5199

application_regions:
  SingleMu_region: ((tau1_pt > {mu_th}  && abs(tau1_eta) < 2.4) ||  (tau2_pt > {mu_th}  && abs(tau2_eta) < 2.4))
  CrossMuTau_region: (tau1_pt > 22 && abs(tau1_eta) < 2.1 && tau2_pt > 32 && abs(tau2_eta) < 2.1)
  SingleEle_region: ((tau1_pt > {ele_th}  && abs(tau1_eta) < 2.5) || (tau2_pt > {ele_th}  && abs(tau2_eta) < 2.5))
  CrossEleTau_region: (tau1_pt > 25 && abs(tau1_eta) < 2.1 && tau2_pt > 35 && abs(tau2_eta) < 2.1)
  diTau_region: (tau1_pt > 40 && abs(tau1_eta) < 2.1 && tau2_pt > 40 && abs(tau2_eta) < 2.1)
  diTauJet_region: (tau1_pt > 35 && abs(tau1_eta) < 2.1 && tau2_pt > 35 && abs(tau2_eta) < 2.1 )  # && Jet_pt>60)
  SingleTau_region: (((tau1_pt > {tau_th} && abs(tau1_eta) < 2.1) || (tau2_pt > {tau_th} && abs(tau2_eta) < 2.1)) )
  # MET_region: (!(Legacy_region) && !(SingleTau_region))

category_definition:

  baseline: "return true;"
  inclusive: "b2_pt>0"
  boosted: "SelectedFatJet_p4[fatJet_sel && SelectedFatJet_pt>300 && abs(SelectedFatJet_eta)<2.5 && SelectedFatJet_msoftdrop > 80 && SelectedFatJet_msoftdrop < 170 && SelectedFatJet_particleNet_XbbVsQCD>={pNetWP}].size()>0"
  res2b: "nSelBtag == 2 && !(boosted)"
  res1b: "nSelBtag == 1 && !(boosted)"

singleMu_th:
  "Run2_2016": 26
  "Run2_2016_HIPM": 26
  "Run2_2017": 29
  "Run2_2018": 26
  "Run3_2022": 26
  "Run3_2022EE": 26
  "Run3_2023": 26
  "Run3_2023BPix": 26
  "Run3_2024": 26
  "Run3_2025": 26
  "Run3_2026": 26

singleEle_th:
  "Run2_2016": 26
  "Run2_2016_HIPM": 26
  "Run2_2017": 33
  "Run2_2018": 33
  "Run3_2022": 32
  "Run3_2022EE": 32
  "Run3_2023": 32
  "Run3_2023BPix": 32
  "Run3_2024": 32
  "Run3_2025": 32
  "Run3_2026": 32

singleTau_th:
  "Run2_2016": 130
  "Run2_2016_HIPM": 130
  "Run2_2017": 190
  "Run2_2018": 190
  "Run3_2022": 190
  "Run3_2022EE": 190
  "Run3_2023": 190
  "Run3_2023BPix": 190
  "Run3_2024": 190
  "Run3_2025": 190
  "Run3_2026": 190

eTau_th:
  "Run2_2016":
  "Run2_2016_HIPM":
  "Run2_2017":
  "Run2_2018":
  "Run3_2022":
  "Run3_2022EE":
  "Run3_2023":
  "Run3_2023BPix":

muTau_th:
  "Run2_2016":
  "Run2_2016_HIPM":
  "Run2_2017":
  "Run2_2018":
  "Run3_2022":
  "Run3_2022EE":
  "Run3_2023":
  "Run3_2023BPix":

btag_wps:
  res2b: Medium
  res1b: Medium
  boosted: Loose

mass_cut_limits:
  bb_m_vis:
    boosted:
      - 30
      - 450
    other:
      - 40
      - 270
  tautau_m_vis:
    - 15
    - 130

scales:
  - Up
  - Down

TTCR_mass_limits:
  eTau:
    - 15
    - 130
  muTau:
    - 15
    - 130
  muMu:
    - 70
    - 100
  tauTau:
    - 15
    - 130
  eE:
    - 70
    - 100
# preVFP == APV == HIPM
unc_2018:
  - JES_BBEC1_2018
  - JES_Absolute_2018
  - JES_EC2_2018
  - JES_HF_2018
  - JES_RelativeSample_2018
unc_2017:
  - JES_BBEC1_2017
  - JES_Absolute_2017
  - JES_EC2_2017
  - JES_HF_2017
  - JES_RelativeSample_2017
unc_2016preVFP:
  - JES_BBEC1_2016preVFP
  - JES_Absolute_2016preVFP
  - JES_EC2_2016preVFP
  - JES_HF_2016preVFP
  - JES_RelativeSample_2016preVFP
unc_2016postVFP:
  - JES_BBEC1_2016postVFP
  - JES_Absolute_2016postVFP
  - JES_EC2_2016postVFP
  - JES_HF_2016postVFP
  - JES_RelativeSample_2016postVFP

uncs_to_exclude:
  Run3_2022: [ ]
  Run3_2022EE: [ ]
  Run3_2023: [ ]
  Run3_2023BPix: [ ]
  Run3_2024: [ ]
  Run3_2025: [ ]
  Run3_2026: [ ]
  Run2_2018:
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
  Run2_2017:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
  Run2_2016:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
  Run2_2016_HIPM:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
bjet_vars:
  - b1_pt
  - b2_pt
  - b1_eta
  - b2_eta

FatJetObservables:
  - area
  - btagCSVV2
  - btagDDBvLV2
  - btagDeepB
  - btagHbb
  - deepTagMD_HbbvsQCD
  - deepTagMD_ZHbbvsQCD
  - deepTagMD_ZbbvsQCD
  - deepTagMD_bbvsLight
  - deepTag_H
  - jetId
  - msoftdrop
  - nBHadrons
  - nCHadrons
  - nConstituents
  - rawFactor
  - particleNetMD_QCD
  - particleNetMD_Xbb
  - particleNet_HbbvsQCD
  - particleNet_mass
  - particleNet_QCD
  - particleNet_XbbVsQCD
  - particleNetLegacy_QCD
  - particleNetLegacy_Xbb
  - particleNetLegacy_mass
  - particleNetWithMass_QCD
  - particleNetWithMass_HbbvsQCD
  - particleNet_massCorr
  - p4
  - pt
  - eta
  - phi
  - mass

var_only_boosted:
  - bbtautau_mass
  - SelectedFatJet_area_boosted
  - SelectedFatJet_btagCSVV2_boosted
  - SelectedFatJet_btagDDBvLV2_boosted
  - SelectedFatJet_btagDeepB_boosted
  - SelectedFatJet_btagHbb_boosted
  - SelectedFatJet_deepTagMD_HbbvsQCD_boosted
  - SelectedFatJet_deepTagMD_ZHbbvsQCD_boosted
  - SelectedFatJet_deepTagMD_ZbbvsQCD_boosted
  - SelectedFatJet_deepTagMD_bbvsLight_boosted
  - SelectedFatJet_deepTag_H_boosted
  - SelectedFatJet_jetId_boosted
  - SelectedFatJet_msoftdrop_boosted
  - SelectedFatJet_nBHadrons_boosted
  - SelectedFatJet_nCHadrons_boosted
  - SelectedFatJet_nConstituents_boosted
  - SelectedFatJet_rawFactor_boosted
  - SelectedFatJet_particleNetMD_QCD_boosted
  - SelectedFatJet_particleNetMD_Xbb_boosted
  - SelectedFatJet_particleNet_HbbvsQCD_boosted
  - SelectedFatJet_particleNet_mass_boosted
  - SelectedFatJet_particleNet_QCD_boosted
  - SelectedFatJet_particleNet_XbbVsQCD_boosted
  - SelectedFatJet_particleNetLegacy_QCD_boosted
  - SelectedFatJet_particleNetLegacy_Xbb_boosted
  - SelectedFatJet_particleNetLegacy_mass_boosted
  - SelectedFatJet_particleNetWithMass_QCD_boosted
  - SelectedFatJet_particleNetWithMass_HbbvsQCD_boosted
  - SelectedFatJet_particleNet_massCorr_boosted
  - SelectedFatJet_p4_boosted
  - SelectedFatJet_pt_boosted
  - SelectedFatJet_eta_boosted
  - SelectedFatJet_phi_boosted
  - SelectedFatJet_mass_boosted
  - SelectedFatJet_particleNetLegacy_mass_boosted
  - SelectedFatJet_mass_boosted
  - SelectedFatJet_msoftdrop_boosted
  - bb_m_vis_softdrop
  - bb_m_vis_pnet
  - bb_m_vis_fj

unc_to_not_consider_boosted:
  - PUJetID
  - JER
  - JES_FlavorQCD
  - JES_RelativeBal
  - JES_HF
  - JES_BBEC1
  - JES_EC2
  - JES_Absolute
  - JES_Total
  - JES_BBEC1_2018
  - JES_Absolute_2018
  - JES_EC2_2018
  - JES_HF_2018
  - JES_RelativeSample_2018
  - bTagSF_Loose_btagSFbc_correlated
  - bTagSF_Loose_btagSFbc_uncorrelated
  - bTagSF_Loose_btagSFlight_correlated
  - bTagSF_Loose_btagSFlight_uncorrelated
  - bTagSF_Medium_btagSFbc_correlated
  - bTagSF_Medium_btagSFbc_uncorrelated
  - bTagSF_Medium_btagSFlight_correlated
  - bTagSF_Medium_btagSFlight_uncorrelated
  - bTagSF_Tight_btagSFbc_correlated
  - bTagSF_Tight_btagSFbc_uncorrelated
  - bTagSF_Tight_btagSFlight_correlated
  - bTagSF_Tight_btagSFlight_uncorrelated
  - bTagShapeSF_lf
  - bTagShapeSF_hf
  - bTagShapeSF_lfstats1
  - bTagShapeSF_lfstats2
  - bTagShapeSF_hfstats1
  - bTagShapeSF_hfstats2
  - bTagShapeSF_cferr1
  - bTagShapeSF_cferr2

payload_producers:
  ggF_DNN:
    producers_module_name: Analysis.DNN_application
    producer_name: DNNProducer
    channels:
      - eTau
      - muTau
      - tauTau
    dependencies:
    model_dir: "config/nn_models/"
    version: "model_fold{}_moe"
    features:
      # - entry_index
      - luminosityBlock
      - run
      - event
      - tau1_pt
      - tau1_eta
      - tau1_phi
      - tau1_mass
      - tau1_decayMode
      - tau1_charge
      - tau2_pt
      - tau2_eta
      - tau2_phi
      - tau2_mass
      - tau2_decayMode
      - tau2_charge
      - b1_pt
      - b1_eta
      - b1_phi
      - b1_mass
      - b1_btagDeepFlavB
      - b1_btagPNetCvB
      - b1_btagPNetCvL
      - b1_HHbtag
      - b2_pt
      - b2_eta
      - b2_phi
      - b2_mass
      - b2_btagDeepFlavB
      - b2_btagPNetCvB
      - b2_btagPNetCvL
      - b2_HHbtag
      - SelectedFatJet_pt_boosted
      - SelectedFatJet_eta_boosted
      - SelectedFatJet_phi_boosted
      - SelectedFatJet_mass_boosted
      - met_pt
      - met_phi
      - met_covXX
      - met_covXY
      - met_covYY
      - Hbb_isValid
      - boosted_baseline
      - channelId
      # - X_mass
      # - X_spin
    columns: # don't change the order of those columns
      - HH
      - TT
      - DY
    n_cpus: 4
    max_runtime: 8.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    class_names:
      - Signal
      - TT
      - DY
